---
title: "Report for June 29th Data"
author: "Adam Levin"
date: "7/4/2021"
output: html_document
---

```{r, echo=FALSE, message=FALSE,  include=FALSE}
#necessary libraries and data
library(dplyr)
library(tidyr)
fluxes = readr::read_csv("fluxes.csv")
collar_map = readr::read_csv("collar_map.csv")
```

# **Influence of Biotic Interactions on Resiliance to Storm Conditions**

### **Dataset Overview**   
The data set is a set of ofas set of data.

### **Relevant Points**
```{R, echo = FALSE}
#shape into a single dataset with relevant columns
fluxesTidy = 
  (fluxes %>% 
    gather(date, value, 2:7))
collarMapTidy = 
  collar_map %>% select(-LI8100A_Port, -Group, -Plot)
collarInfoNoFilter = #no filter needed here
  collarMapTidy %>% left_join(fluxesTidy, "Collar")
```

Number of Observations = **`summarize(collarInfoNoFilter`**

Minimum Flux = **`r sort(collarInfoNoFilter[3], decreasing = FALSE)[1]`**

Maximum Flux =  

First Date = 

Final Date = 

### **Ending Session Info**
```{r, echo = FALSE}
sessionInfo()
```
