---
title: "Soil Respiration Database Report"
author: "Adam Levin"
date: "7/11/2021"
output: html_document
---

Libraries used and source of data read in:
```{r, message=FALSE, warning=FALSE}
#Libraries
library(tidyr)
library(dplyr)
library(ggplot2)
library(Rcpp)
library(sp)
library(raster)
library(randomForest)
library(ROCR)

#Data source
srdbData = read.csv("srdb-master/srdb-data.csv")

```


**Number of Entries by Ecosystem Type and Initial Distribution:**
```{r, echo = FALSE}
#choose relevant categories
srdbManagable = srdbData %>% dplyr::select(Longitude, Latitude, Study_midyear, Ecosystem_type, Manipulation, Rs_annual, RC_annual, Soil_drainage, Partition_method, Leaf_habit) %>% unique() 

#rc annual distribution
srdbManagable %>% ggplot(aes(RC_annual)) + geom_histogram(bins = 50)

#number of observations (rows) by ecosystem type
#get rid of whitespace first
srdbManagable$Ecosystem_type = srdbManagable$Ecosystem_type %>% trimws(c("both"))

#group by ecosystem and remove empty entries
groupedByEcoType = srdbManagable %>%  filter(srdbManagable$Ecosystem_type != "") %>% group_by(Ecosystem_type)

ecosystemList = groupedByEcoType %>% dplyr::select(Ecosystem_type)

print(ecosystemList %>% summarize(n()))

```

**Annual RC Visualization:**
```{r, warning=FALSE, echo=FALSE}
#graph annual RC against lattitude with color coding by ecosystem and size by annual RS
ggplot(groupedByEcoType, aes(RC_annual, Latitude)) + geom_point(aes(color = Ecosystem_type, size = Rs_annual)) + xlim(-.1, 1) + ylim(-50, 70) + theme_classic() + labs(Title = "RC_annual by Latitude", color = "Ecosystem Type")
```

**WorldClim Database Addition**   
```{r, echo = FALSE, message=FALSE, warning=FALSE}

#get data
precip <- getData("worldclim", var = "prec", res = 10, download = !file.exists("wc10/wc10/precip1.hdr"))
tmean <- getData("worldclim", var = "tmean", res = 10, download = !file.exists("wc10/wc10/tmean1.hdr"))

#select coordinates from srdb and filter by RC_annual and coords being present
srdbCoords = srdbManagable %>% dplyr::filter(RC_annual != "N/A" & Longitude != "N/A" & Latitude != "N/A")

# Extract srdb location data from worldclim data for precip...
raster::extract(precip, srdbCoords[1:2]) -> precip_coords
apply(precip_coords, 1, sum) -> map_srdb

# ...and tmean
raster::extract(tmean,srdbCoords[1:2]) -> tmean_vals
apply(tmean_vals, 1, mean) -> mat_srdb
cbind(srdbCoords, mat_srdb)  %>%
  # Temp data is stored in degC * 10, so we need to divide to get back to degC
  mutate(mat_srdb = mat_srdb / 10) -> mat_data

#combine all climate data w/ srdb
srdbFinal = cbind(mat_data, map_srdb)

#print first 20 rows
srdbFinal[1:20,]

``` 

**Visualizations of RC_annual and climate **
```{r,, echo = FALSE}

world_map <- map_data("world")
srdbFinal %>% ggplot(aes(Title = "Studies across World by Percipitation", Longitude, Latitude, color = map_srdb)) + geom_map(data = world_map, map = world_map, aes(long, lat, map_id = region), color = "darkgrey", fill = "white", size = 0.4
) + geom_point(size = srdbFinal$RC_annual * 2) + scale_color_gradient(low = "aquamarine", high = "dodgerblue4") + labs(color = "Mean Annual Percipitation")

srdbFinal %>% ggplot(aes(mat_srdb, RC_annual, color = mat_srdb)) + scale_color_gradient(low = "yellow1", high = "red1") + geom_point(size = srdbFinal$map_srdb* .001) + labs(x = "Mean Annual Temperature", color = "Mean Annual Temperature", size = "Mean Annual Percipitation ")

srdbFinal %>% ggplot(aes(Latitude, mat_srdb)) + geom_point() + labs(y = "Mean Annual Temperature")

srdbFinal %>% ggplot(aes(mat_srdb, map_srdb)) + geom_point() + labs(x = "Mean Annual Temperature", y = "Mean Annual Percipitation")
```  
  
**Random Forest Addition**
```{r}
#random seed for reprodcution
set.seed(37)

#size of testing set 
data_set_size = floor(nrow(srdbFinal)*.8)

#choosing testing set
indexes = sample(1:nrow(srdbFinal), size = data_set_size)

#set creation
training = srdbFinal[indexes, ]
validationSet = srdbFinal[-indexes, ]

#training
RcRandFor = randomForest(formula = RC_annual ~ ., data = training, na.action = na.omit, ntree = 100, mtry = 2, importance = TRUE)

#print importance plot
varImpPlot(x = RcRandFor, main = "Importance Plots")

#comparing to validation through confusion matrix
validationSet$prediction = predict(object = RcRandFor, newdata = validationSet[ , -7])

#fitting linear regression
m_prediction = lm(prediction ~ RC_annual, data = validationSet)
print(summary(m_prediction))

#qplot of predicted vs observed of RC_annual
qplot(RC_annual, prediction, data = validationSet, xlab = "Actual RC", ylab = "Predicted RC") + geom_abline() + geom_smooth(method = lm) 

#ROC Curves (not applicable? Use ecosystemtype or other qualitative instead?)
#probability of new observations belonging to a class
#ROCcurvePredict = predict(object = RcRandFor, newdata = validationSet[ , -7], type = "prob")

```

**Session Information**
```{r, echo = FALSE}
sessionInfo()

```
